# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    repository: 'task-api'
    tags: '$(Build.BuildId)'
  displayName: 'Build Docker image'
